{% set name = "orjson" %}
{% set version = "3.6.4" %}
{% set rust_nightly_version = "2021-10-01" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: f8dbc428fc6d7420f231a7133d8dff4c882e64acb585dcf2fda74bdcfe1a6d9d
  - url: https://static.rust-lang.org/dist/{{ rust_nightly_version }}/rust-nightly-x86_64-unknown-linux-gnu.tar.gz  # [linux64]
    sha256: 070d28cb4d8417f39d769a84c7e78d9acefc3f81562b22fd58dfeed7df2b0c96  # [linux64]
  - url: https://static.rust-lang.org/dist/{{ rust_nightly_version }}/rust-nightly-powerpc64le-unknown-linux-gnu.tar.gz  # [ppc64le]
    sha256: f242dda4f9902bdb88d691274f6344927f3fc904dad07e7e09ec90cdedcd5965  # [ppc64le]
  - url: https://static.rust-lang.org/dist/{{ rust_nightly_version }}/rust-nightly-aarch64-unknown-linux-gnu.tar.gz  # [aarch64]
    sha256: 82224f878027f5b4cac7bc874eb9ecc511b8d1fad0e6fba452e81f4204aeeb62  # [aarch64]
  - url: https://static.rust-lang.org/dist/{{ rust_nightly_version }}/rust-nightly-x86_64-apple-darwin.tar.gz  # [osx]
    sha256: 7062b29645053ac5e7fc24bf441fd9caf7389994ab92478d3ab9108b7e6851c7  # [osx]
  - url: https://static.rust-lang.org/dist/{{ rust_nightly_version }}/rust-nightly-x86_64-pc-windows-msvc.tar.xz  # [win]
    sha256: a1500d1d0f589db8d42e282d54f860ef82e8ab59a064fc6395b74f453bccfdbd  # [win]
    folder: rust-nightly
  - url: https://static.rust-lang.org/dist/{{ rust_nightly_version }}/rust-nightly-aarch64-apple-darwin.tar.gz  # [target_platform == 'osx-arm64']
    sha256: 532839cf9a1f2ec0b1471c8997b04c5711677d0b5a5c5c3c4efbe7c5c7941798  # [target_platform == 'osx-arm64']
    folder: rust-nightly-aarch64-apple-darwin  # [target_platform == 'osx-arm64']

build:
  number: 0
  skip: true  # [py<37]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('c') }}                 # [not win]
    - posix                               # [win]
  host:
    - python
    - pip
    - maturin >=0.11.4,<0.12
    - toml
  run:
    - python

test:
  imports:
    - orjson

about:
  home: https://github.com/ijl/orjson
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
  summary: orjson is a fast, correct JSON library for Python.
  doc_url: https://github.com/ijl/orjson
  dev_url: https://github.com/ijl/orjson

extra:
  recipe-maintainers:
    - EntPyle
    - nehaljwani
    - synapticarbors
