{% set name = "orjson" %}
{% set version = "3.4.7" %}
{% set rust_nightly_version = "2021-01-11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 8bc99f175d7ea42b5faf18f3b503423bce4631c3605f699e014232cc329fb14e
  - url: https://static.rust-lang.org/dist/{{ rust_nightly_version }}/rust-nightly-x86_64-unknown-linux-gnu.tar.gz       # [linux64]
    sha256: 32c22b990b9526593dfb0471fb318a05fce6b5c763d83809d485a656e41deb96                                             # [linux64]
  - url: https://static.rust-lang.org/dist/{{ rust_nightly_version }}/rust-nightly-powerpc64le-unknown-linux-gnu.tar.gz  # [ppc64le]
    sha256: 67f13b843e4c530b0c61a17bcc5372ac4f45f9b2291adea0ee3bf7e7c1e8bfe2                                             # [ppc64le]
  - url: https://static.rust-lang.org/dist/{{ rust_nightly_version }}/rust-nightly-aarch64-unknown-linux-gnu.tar.gz      # [aarch64]
    sha256: 802f6772566d70218f1f8303078e5c5c55232a2d32058ca485be8531b50d09dd                                             # [aarch64]
  - url: https://static.rust-lang.org/dist/{{ rust_nightly_version }}/rust-nightly-x86_64-apple-darwin.tar.gz            # [osx]
    sha256: da7eddd5e25c2166c254053d41b7c40024e0f34fe9a7013c0b49c868b5cf9a5a                                             # [osx]
  - url: https://static.rust-lang.org/dist/{{ rust_nightly_version }}/rust-nightly-x86_64-pc-windows-msvc.tar.gz         # [win]
    sha256: 1fa2edaa7da3aa8bf1903603d06d809bff5c1c30eb0eb6d968d8bf2de216f6aa                                             # [win]
    folder: rust-nightly
  - url: https://static.rust-lang.org/dist/{{ rust_nightly_version }}/rust-nightly-aarch64-apple-darwin.tar.gz           # [target_platform == 'osx-arm64']
    sha256: 7d017c5f1fed7d4175dc701c24a2ec1207a4e577923528b8d1f28c0d14f83b35                                             # [target_platform == 'osx-arm64']
    folder: rust-nightly-aarch64-apple-darwin                                                                            # [target_platform == 'osx-arm64']

build:
  number: 0
  skip: true  # [py<36]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('c') }}                 # [not win]
    - posix                               # [win]
  host:
    - python
    - pip
    - maturin >=0.9.0,<0.10
    - toml
  run:
    - python

test:
  imports:
    - orjson

about:
  home: https://github.com/ijl/orjson
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
  summary: orjson is a fast, correct JSON library for Python.
  doc_url: https://github.com/ijl/orjson
  dev_url: https://github.com/ijl/orjson

extra:
  recipe-maintainers:
    - EntPyle
    - nehaljwani
    - synapticarbors
