{% set version = "3.9.0" %}

package:
  name: orjson
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/orjson/orjson-{{ version }}.tar.gz
  sha256: f6dd27c71cd6e146795f876449a8eae74f67ae1e4e244dfc1203489103eb2d94

build:
  number: 0
  skip: true  # [py<37]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - maturin >=0.13,<2                   # [build_platform != target_platform]
    - {{ compiler('c') }}                 # [not win]
    - {{ compiler('rust') }}
    - posix                               # [win]
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - toml
    - maturin >=0.13,<2
  run:
    - python

test:
  imports:
    - orjson
  requires:
    - pip
    - mypy
  commands:
    - pip check
    - mypy -m orjson

about:
  home: https://github.com/ijl/orjson
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: orjson is a fast, correct JSON library for Python.
  doc_url: https://github.com/ijl/orjson
  dev_url: https://github.com/ijl/orjson

extra:
  recipe-maintainers:
    - EntPyle
    - nehaljwani
    - synapticarbors
