{% set version = "3.8.5" %}

package:
  name: orjson
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/orjson/orjson-{{ version }}.tar.gz
  sha256: 77a3b2bd0c4ef7723ea09081e3329dac568a62463aed127c1501441b07ffc64b

build:
  number: 1
  skip: true  # [py<37]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - maturin >=0.13,<0.15                # [build_platform != target_platform]
    - {{ compiler('c') }}                 # [not win]
    - {{ compiler('rust') }}
    - posix                               # [win]
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - toml
    - maturin >=0.13,<0.15
  run:
    - python

test:
  imports:
    - orjson
  requires:
    - pip
    - mypy
  commands:
    - pip check
    - mypy -m orjson

about:
  home: https://github.com/ijl/orjson
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: orjson is a fast, correct JSON library for Python.
  doc_url: https://github.com/ijl/orjson
  dev_url: https://github.com/ijl/orjson

extra:
  recipe-maintainers:
    - EntPyle
    - nehaljwani
    - synapticarbors
